apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
type: Opaque
stringData:
  credentials: |-
    [promode]
    aws_access_key_id     = $promode_aws_access_key_id
    aws_secret_access_key = $promode_aws_secret_access_key

    [ptr]
    aws_access_key_id     = $ptr_aws_access_key_id
    aws_secret_access_key = $ptr_aws_secret_access_key
  config: |-
    [profile promode]
    region = us-east-1
    output = json
    [profile ptr]
    region = us-east-1
    output = json
