apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: read-directory
  namespace: tekton-pipelines
spec:
  params:
    - name: directory
      type: string
  workspaces:
    - name: shared-data
  steps:
    - name: read-directory
      image: ubuntu
      script: ls -a $(workspaces.shared-data.path)/$(params.directory)
